name: Check Notarization

on:
  workflow_dispatch:
    inputs:
      id:
        description: Notarization ID
        required: true
        type: string

jobs:

  eclipse-distro-build:
    runs-on: macos-latest
    steps:
    - name: Notarization Logs
      run: |
        xcrun notarytool log ${{ inputs.id }} --apple-id ${{ secrets.VMWARE_APPLE_USER }} --team-id ${{ secrets.VMWARE_APPLE_TEAM_ID }} --password ${{ secrets.VMWARE_APPLE_PASSWORD }}
