name: Publish Release - Eclipse

concurrency:
  group: release-eclipse
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      ls_version:
        description: The suffix of the p2 repo URL in S3 (i.e. 2023-11-01)
        required: true
        type: string
      release_version:
        description: Release version (i.e. 4.20.1)
        required: true
        type: string
      eclipse_latest:
        description: Latest eclipse release version (i.e. e4.30)
        required: true
        type: string

permissions:
  contents: write

jobs:

  aggregate-ls-extension-update-site:
    uses: ./.github/workflows/aggregate-ls-extensions-update-site.yml
    with:
      version: ${{ inputs.ls_version }}
    secrets: inherit

  aggregate-distro-update-site:
    uses: ./.github/workflows/aggregate-distro-update-sites.yml
    with:
      version: ${{ inputs.release_version }}.RELEASE
      latest: ${{ inputs.eclipse_latest }}
    secrets: inherit

  backup-release-on-gcp:
    uses: ./.github/workflows/backup-eclipse-releases-to-gcp.yml
    with:
      ls_version: ${{ inputs.ls_version }}
      release_version: ${{ inputs.release_version }}.RELEASE
    secrets: inherit

  create-github-release:
    uses: ./.github/workflows/create-gh-release.yml
    with:
      version: ${{ inputs.release_version }}.RELEASE
    secrets: inherit

#  announce-release:
#    needs: [ aggregate-ls-extension-update-site, aggregate-distro-update-site, create-github-release ]
#    uses: ./.github/workflows/announce-release.yml
#    with:
#      version: ${{ inputs.release_version }}
#    secrets: inherit
