name: Upload nightly-distributions.html form the Repo to S3

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'eclipse-distribution/common/html/nightly-distributions.html'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.CDN_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_S3_SECRET_KEY  }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_ENDPOINT_URL_S3:  ${{ secrets.CDN_S3_ENDPOINT }}
  AWS_S3_BUCKET: ${{ secrets.CDN_BUCKET }}/spring-tools
  DOWNLOAD_URL_ROOT: https://cdn.spring.io/spring-tools

jobs:

  upload-nightly-downloads-s3-cache:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          sparse-checkout: |
            .github
            eclipse-distribution/common/html
      - name: Upload nightly-distributions.html
        run: |
          echo "Removing old nightly-distributions.html from s3..."
          aws s3 rm s3://$AWS_S3_BUCKET/snapshot/STS4/nightly-distributions.html
          echo "Uploading new nightly-distributions.html to s3..."
          aws s3 cp ./eclipse-distribution/common/html/nightly-distributions.html s3://$AWS_S3_BUCKET/snapshot/STS4/nightly-distributions.html --no-progress
