name: Wipe out temp build artifacts

# configure manual trigger
on:
  workflow_dispatch:
#on:
#  push:
#    branches:
#      - 'main'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.CDN_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.CDN_S3_SECRET_KEY  }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_ENDPOINT_URL_S3:  ${{ secrets.CDN_S3_ENDPOINT }}
  AWS_S3_BUCKET: ${{ secrets.CDN_BUCKET }}/spring-tools

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Remove Temp Build Artifacts from S3
        id: cleanup-s3-temp-storage
        run: |
          aws s3 rm s3://${AWS_S#_BUCKET}/sts4-distro-ci-temp --recursive --exclude "*" --include "*.zip"

